name: ceph_osdi06

ships:
  node1: {ip: &n1ip 192.168.140.101}
  node2: {ip: &n2ip 192.168.140.107}
  node3: {ip: &n3ip 192.168.140.108}
  node4: {ip: &n4ip 192.168.140.118}
  node5: {ip: &n5ip 192.168.140.128}
  node6: {ip: &n6ip 192.168.140.132}
  node7: {ip: &n7ip 192.168.140.144}
  node8: {ip: &n8ip 192.168.140.147}

ship_defaults:
  docker_port: 2375

  # this is currently ignored, but we're putting it here for later reference and
  # to exemplify how we would like this to be given. This is taken from
  # cloud-config's cloud-init syntax for disk formatting and configuration modules
  # {
  disk_setup:
    /dev/sdb1:
      table_type: 'mbr'
      layout: True
      overwrite: True
    /dev/sde1:
      table_type: 'mbr'
      layout: True
      overwrite: True

  fs_setup:
    - label:  None
      filesystem: 'ext4'
      device: '/dev/sdb1'
      partition: 'auto'
    
    - label: None
      filesystem: 'xfs'
      device: '/dev/sde1'
      partition: 'auto'

  mounts:
    - [ sdb1, /mnt/hdd, "auto" ]
    - [ sde1, /mnt/ssd, "auto", "rw,noexec,nodev,noatime,nodiratime,nobarrier", "0", "0" ]

  mount_default_fields: [ None, None, "auto", "defaults,nobootwait", "0", "2" ]
  # }

service_variables:
  ceph-conf-path: &cephconf /user/ivo/cephconf
  osd-data-path: &data /mnt/hdd/ivo/ceph/
  journal-path: &journal /mnt/ssd/ivo/ceph/

services:
  ceph-mon:
    image: scottlaird/ceph-mon
    instances:
      ceph-mon-0:
        ship: node7
        env:
          MON_IP: *n1ip
          MON_NAME: mymon
        volumes:
          /etc/ceph: *cephconf
        net: host
  ceph-osd:
    image: scottlaird/ceph-osd
    requires: [ceph-mon]
    instances:
      ceph-osd-0:
        ship: node2
        env:
          OSD_ID: 0
          HOSTNAME: *n2ip
#JOURNAL: /var/lib/ceph/osd/journal_dir/journal
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data
        net: host
#/var/lib/ceph/osd/journal_dir: *journal
      ceph-osd-1:
        ship: node3
        env:
          OSD_ID: 1
          HOSTNAME: *n3ip
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data
        net: host
      ceph-osd-2:
        ship: node4
        env:
          OSD_ID: 2
          HOSTNAME: *n4ip
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data
        net: host
