_globals_defaults:
  V1: &cephconf {{ env.CEPHCONF }}
  V2: &resultsfolder {{ env.RESULTS_FOLDER }}
  V3: &secs {{ env.SECS }}
  V4: &benchtype {{ env.EXP_TYPE }}
  V5: &size {{ env.SIZE }}
  V6: &threads {{ env.THREADS }}
  V7: &expname {{ env.EXP }}

name: ceph_osdi06

ships:
  node0: {ip: &n0ip 192.168.141.101}
  node1: {ip: 192.168.141.107}
  node2: {ip: 192.168.141.108}
  node3: {ip: 192.168.141.118}
  node4: {ip: 192.168.141.132}
  node5: {ip: 192.168.141.147}
  node6: {ip: 192.168.141.129}

ship_defaults:
  docker_port: 2375

# this is currently ignored, but we're putting it here for later reference and
# to exemplify how we would like this to be given. This is taken from
# cloud-config's cloud-init syntax for disk formatting and configuration modules
# {
  disk_setup:
    /dev/sdb1:
      table_type: 'mbr'
      layout: True
      overwrite: True

  fs_setup:
    - label:  None
      filesystem: 'xfs'
      device: '/dev/sdb1'
      partition: 'auto'

    - label:  None
      filesystem: 'xfs'
      device: '/dev/sdc1'
      partition: 'auto'

    - label:  None
      filesystem: 'xfs'
      device: '/dev/sdd1'
      partition: 'auto'

  mounts:
    - [ sdb1, /mnt/hdd1, "auto", "rw,noexec,nodev,noatime,nodiratime,nobarrier", "0", "0" ]
    - [ sdc1, /mnt/hdd2, "auto", "rw,noexec,nodev,noatime,nodiratime,nobarrier", "0", "0" ]
    - [ sdd1, /mnt/hdd3, "auto", "rw,noexec,nodev,noatime,nodiratime,nobarrier", "0", "0" ]

  mount_default_fields: [ None, None, "auto", "defaults,nobootwait", "0", "2" ]
# }

service_variables:
  hdd1: &data1 /mnt/hdd1/ceph/
  hdd2: &data2 /mnt/hdd2/ceph/
  hdd3: &data3 /mnt/hdd3/ceph/

services:
  ceph-mon:
    image: ivotron/ceph-mon:0.87.1
    instances:
      ceph-mon:
        ship: node0
        env:
          MON_IP: *n0ip
          MON_NAME: mymon
        volumes:
          /etc/ceph: *cephconf
        net: host
  ceph-osd:
    image: ivotron/ceph-osd:0.87.1
    requires: [ceph-mon]
    instances:
      ceph-osd-1:
        ship: node1
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        env:
          OSD_ID: 0
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data1
        net: host
      ceph-osd-2:
        ship: node2
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        env:
          OSD_ID: 1
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data1
        net: host
      ceph-osd-3:
        ship: node3
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        env:
          OSD_ID: 2
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data1
        net: host
      ceph-osd-4:
        ship: node4
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        env:
          OSD_ID: 3
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data1
        net: host
      ceph-osd-5:
        ship: node5
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        env:
          OSD_ID: 4
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data1
        net: host
      ceph-osd-6:
        ship: node1
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        env:
          OSD_ID: 5
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data2
        net: host
      ceph-osd-7:
        ship: node2
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        env:
          OSD_ID: 6
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data2
        net: host
      ceph-osd-8:
        ship: node3
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        env:
          OSD_ID: 7
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data2
        net: host
      ceph-osd-9:
        ship: node4
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        env:
          OSD_ID: 8
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data2
        net: host
      ceph-osd-10:
        ship: node5
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        env:
          OSD_ID: 9
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data2
        net: host
      ceph-osd-11:
        ship: node1
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        env:
          OSD_ID: 10
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data3
        net: host
      ceph-osd-12:
        ship: node2
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        env:
          OSD_ID: 11
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data3
        net: host
      ceph-osd-13:
        ship: node3
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        env:
          OSD_ID: 12
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data3
        net: host
      ceph-osd-14:
        ship: node4
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        env:
          OSD_ID: 13
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data3
        net: host
      ceph-osd-15:
        ship: node5
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        env:
          OSD_ID: 14
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *data3
        net: host
  ceph-radosbench:
    image: ivotron/radosbench:0.2
    requires: [ceph-osd]
    env:
      TYPE: *benchtype
      SECS: *secs
      THREADS: *threads
      SIZE: *size
      POOL: test
    instances:
      ceph-radosbench-1:
        ship: node6
        env:
          OUTFILE: /var/lib/ceph/out
        volumes:
          /etc/ceph: *cephconf
          /var/lib/ceph: *resultsfolder
  ceph-osd-cleanup:
    image: stackbrew/ubuntu:trusty
    requires: [ceph-osd]
    instances:
      ceph-osd-cleanup-1:
        ship: node1
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data1
      ceph-osd-cleanup-2:
        ship: node2
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data1
      ceph-osd-cleanup-3:
        ship: node3
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data1
      ceph-osd-cleanup-4:
        ship: node4
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data1
      ceph-osd-cleanup-5:
        ship: node5
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data1
      ceph-osd-cleanup-6:
        ship: node1
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data2
      ceph-osd-cleanup-7:
        ship: node2
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data2
      ceph-osd-cleanup-8:
        ship: node3
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data2
      ceph-osd-cleanup-9:
        ship: node4
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data2
      ceph-osd-cleanup-10:
        ship: node5
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data2
      ceph-osd-cleanup-11:
        ship: node1
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data3
      ceph-osd-cleanup-12:
        ship: node2
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data3
      ceph-osd-cleanup-13:
        ship: node3
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data3
      ceph-osd-cleanup-14:
        ship: node4
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data3
      ceph-osd-cleanup-15:
        ship: node5
        command: /bin/sh -c "rm -fr /mnt/*"
        volumes:
          /mnt: *data3
  throttle-check:
    image: stackbrew/ubuntu:trusty
    instances:
      throttle-check-1:
        ship: node1
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        volumes:
          /mnt: *data1
      throttle-check-2:
        ship: node1
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        volumes:
          /mnt: *data2
      throttle-check-3:
        ship: node1
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        volumes:
          /mnt: *data3
      throttle-check-4:
        ship: node2
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        volumes:
          /mnt: *data1
      throttle-check-5:
        ship: node2
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        volumes:
          /mnt: *data2
      throttle-check-6:
        ship: node2
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        volumes:
          /mnt: *data3
      throttle-check-7:
        ship: node3
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        volumes:
          /mnt: *data1
      throttle-check-8:
        ship: node3
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        volumes:
          /mnt: *data2
      throttle-check-9:
        ship: node3
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        volumes:
          /mnt: *data3
      throttle-check-10:
        ship: node4
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        volumes:
          /mnt: *data1
      throttle-check-11:
        ship: node4
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        volumes:
          /mnt: *data2
      throttle-check-12:
        ship: node4
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        volumes:
          /mnt: *data3
      throttle-check-13:
        ship: node5
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:16 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:16 31457280"
        volumes:
          /mnt: *data1
      throttle-check-14:
        ship: node5
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:32 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:32 31457280"
        volumes:
          /mnt: *data2
      throttle-check-15:
        ship: node5
        command: /bin/sh -c "dd if=/dev/zero of=/mnt/here bs=4M count=250 oflag=direct"
        lxc_conf:
          lxc.cgroup.blkio.throttle.write_bps_device: "8:48 31457280"
          lxc.cgroup.blkio.throttle.read_bps_device: "8:48 31457280"
        volumes:
          /mnt: *data3
